<?php
require_once("accommodation.php");
require_once("attraction_site.php");
require_once("country.php");
require_once("currency.php");
require_once("event.php");
require_once("expiration.php");
require_once("financial_year.php");
require_once("gfs.php");
require_once("institution.php");
require_once("location.php");
require_once("meteorological_detail.php");
require_once("reserve.php");
require_once("species.php");
require_once("specimen.php");
require_once("station.php");
require_once("tarrif.php");
require_once("unit.php");
